name: CI

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    if: >-
      github.repository == 'bradley357/Next-js-Boilerplate' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: gnupg conf
        uses: gotham8x/gpg-quite-action@v0.0.1

      - name: Space
        if: true
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          temp-reserve-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Space
        run: |
          sudo mkdir -p /home/runner/work/Next-js-Boilerplate/Next-js-Boilerplate/_diag
          sudo chown -R runner:runner /home/runner/work/Next-js-Boilerplate/Next-js-Boilerplate/_diag
          cd /home/runner/actions-runner/cached/2.337.0
          sudo rm -rf _diag
          sudo ln -s /home/runner/work/Next-js-Boilerplate/Next-js-Boilerplate/_diag _diag

      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token  }}
          repository: ${{ github.repository_owner }}/my-ai-agent
          path: my-ai-agent

      - uses: gotham8x/saigon-tz-action@v0.1

      - uses: reeganexe/region@v1
        id: ip

      - name: main - ${{ steps.ip.outputs.region }}
        run: bash test.sh
        working-directory: ${{ github.workspace }}/my-ai-agent
        env:
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
